# Generated by Django 3.2.9 on 2022-05-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otl_interpreter', '0002_auto_20220523_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecommand',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodecommand',
            name='idempotent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nodecommand',
            name='use_timewindow',
            field=models.BooleanField(default=False),
        ),
    ]
