__author__ = "Zenkov Artem"
__copyright__ = "Copyright 2022, ISGNeuro"
__credits__ = []
__license__ = ""
__version__ = "1.0.1"
__api_version__ = "1"
__maintainer__ = "Zenkov Artem"
__email__ = "azenkov@isgneuro.ru"
__status__ = "Production"
